<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Shahnozas-MacBook-Air.local" failures="1" tests="5" name="TestNGProject" time="73.534" errors="0" timestamp="2023-02-16T18:28:01 MST">
  <testcase classname="com.exelenter.class05._02_HW_AddEmployee" name="addEmployeeTest" time="7.473"/>
  <testcase classname="com.exelenter.class05._02_HW_AddEmployee" name="addEmployeeTest" time="7.45"/>
  <testcase classname="com.exelenter.class05._02_HW_AddEmployee" name="addEmployeeTest" time="21.17">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.class05._02_HW_AddEmployee.addEmployeeTest(_02_HW_AddEmployee.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.class05._02_HW_AddEmployee" name="addEmployeeTest" time="7.407"/>
  <testcase classname="com.exelenter.class05._02_HW_AddEmployee" name="addEmployeeTest" time="7.896"/>
</testsuite> <!-- TestNGProject -->
