<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Shahnozas-MacBook-Air.local" failures="4" tests="4" name="Excel Test" time="104.294" errors="0" timestamp="2023-02-18T07:48:59 MST">
  <testcase classname="com.exelenter.class05._02_AddEmployeeFromExcel" name="addEmployeeTest" time="22.4">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.class05._02_AddEmployeeFromExcel.addEmployeeTest(_02_AddEmployeeFromExcel.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.class05._02_AddEmployeeFromExcel" name="addEmployeeTest" time="21.067">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.class05._02_AddEmployeeFromExcel.addEmployeeTest(_02_AddEmployeeFromExcel.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.class05._02_AddEmployeeFromExcel" name="addEmployeeTest" time="21.54">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.class05._02_AddEmployeeFromExcel.addEmployeeTest(_02_AddEmployeeFromExcel.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
  <testcase classname="com.exelenter.class05._02_AddEmployeeFromExcel" name="addEmployeeTest" time="21.104">
    <failure type="java.lang.RuntimeException" message="Employee is not added. Username or ID already exits.">
      <![CDATA[java.lang.RuntimeException: Employee is not added. Username or ID already exits.
at com.exelenter.class05._02_AddEmployeeFromExcel.addEmployeeTest(_02_AddEmployeeFromExcel.java:69)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- addEmployeeTest -->
</testsuite> <!-- Excel Test -->
